from __future__ import annotations

from typing import Final

CsvValue = str | int | float

PEAK_EVOLUTION_FIELDS: Final[tuple[str, ...]] = (
    "sweep_index",
    "sweep_axis",
    "y",
    "shuffle_signed",
    "shuffle_magnitude",
    "a_A",
    "b_A",
    "c_A",
    "line",
    "h",
    "k",
    "l",
    "hkl",
    "two_theta_deg",
    "d_A",
    "q_A-1",
    "multiplicity",
    "F2",
    "LP",
    "I_raw",
    "I_rel_local",
    "I_rel_global",
)
SPECTRA_LONG_FIELDS: Final[tuple[str, ...]] = (
    "sweep_index",
    "sweep_axis",
    "y",
    "shuffle_signed",
    "shuffle_magnitude",
    "two_theta_deg",
    "intensity_rel_local",
    "intensity_rel_global",
)
CURRENT_SPECTRUM_FIELDS: Final[tuple[str, ...]] = (
    "point_index",
    "two_theta_deg",
    "q_primary_A_inv",
    "d_primary_A",
    "intensity_model",
    "intensity_rel_local",
)
CURRENT_PEAK_FIELDS: Final[tuple[str, ...]] = (
    "line_id",
    "line",
    "series_id",
    "h",
    "k",
    "l",
    "hkl",
    "hkl_id",
    "wavelength_A",
    "line_weight",
    "two_theta_deg",
    "d_A",
    "q_A_inv",
    "s_A_inv",
    "form_factor_effective",
    "F_real",
    "F_imag",
    "F2",
    "multiplicity",
    "LP",
    "volume_A3",
    "applied_multiplicity",
    "applied_LP",
    "applied_volume_factor",
    "I_model_peak",
    "I_rel_local",
)
PEAK_EVOLUTION_V2_FIELDS: Final[tuple[str, ...]] = (
    *PEAK_EVOLUTION_FIELDS,
    "step_id",
    "step_label",
    "axis_value",
    "line_id",
    "series_id",
    "wavelength_A",
    "line_weight",
    "s_A_inv",
    "form_factor_effective",
    "F_real",
    "F_imag",
    "volume_A3",
    "applied_multiplicity",
    "applied_LP",
    "applied_volume_factor",
    "I_model_peak",
)
SPECTRA_LONG_V2_FIELDS: Final[tuple[str, ...]] = (
    *SPECTRA_LONG_FIELDS,
    "step_id",
    "step_label",
    "axis_value",
    "a_A",
    "b_A",
    "c_A",
    "primary_energy_keV",
    "primary_wavelength_A",
    "q_primary_A_inv",
    "d_primary_A",
    "intensity_model",
)
SWEEP_STEPS_FIELDS: Final[tuple[str, ...]] = (
    "sweep_index",
    "step_id",
    "step_label",
    "sweep_axis",
    "axis_value",
    "y",
    "shuffle_signed",
    "shuffle_magnitude",
    "a_A",
    "b_A",
    "c_A",
    "primary_energy_keV",
    "primary_wavelength_A",
    "radiation_line_count",
)
SERIES_MAP_FIELDS: Final[tuple[str, ...]] = (
    "series_id",
    "line_id",
    "h",
    "k",
    "l",
    "hkl",
    "hkl_id",
)
